### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by Sushmab27** [liaocyintl/HybridImageMatching#1]
Matching input\query\01.jpg with target image input\target\LOTTERIA\04.jpg
Exception [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "run.py", line 111, in <module>
    match()
  File "run.py", line 86, in match
    M, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, setting.RANSAC_THRESHOLD)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\calib3d\src\fundam.cpp:372: error: (-5:Bad argument) The input arrays should be 2D or 3D point sets in function 'cv::findHomography'

**Comment by liaocyintl-deprecated** [comment]
Hi
It seems you are using opencv 4.1.
The function may be changed in this new version.

Could you please try opencv 3.2.
Please see https://anaconda.org/menpo/opencv3 for installation.

**Comment by Tylersuard** [comment]
I am trying this and getting the same error.  I'm not finding an installation of opencv 3.2 on anaconda that is compatible with python 3.6

**Comment by Tylersuard** [comment]
Here is my code: https://colab.research.google.com/drive/1rKkizM9lPMO_44tj_hlOGQoTrGuwwTmX?usp=sharing

**Comment by liaocyintl-deprecated** [comment]
@Tylersuard hi, there is a error log:
Exception [Errno 13] Permission denied: 'deepmatching/deepmatching-static'
in your notebook.
Did you grant permissions for it?

I haven't try performing this code on Google Colab.
Do you need any special settings on the enviroment?
